name: EggTimer
version: 1.0
author: SpaceManiac
description: A simple plugin to create timed item deposits in chests around the map.
main: com.platymuus.bukkit.eggtimer.EggTimerPlugin
commands:
  eggtimer:
    description: Allows reloading of the EggTimer configuration.
    usage: /eggtimer reload
